import {QUESTIONS,DIMS,VERSION} from './data.js';
import {KEY,fresh,selected,facts,evidence,profile,freeze,stats,setAnswer,restore,label,identity} from './engine.js';
const previewMode=new URLSearchParams(location.search).get('preview')==='result';
const root=document.getElementById('app');let storageOK=true,state=fresh(),screen='home',picked=null,backScreen='play';
if(previewMode){
 for(const q of QUESTIONS.filter(q=>!q.test)){const choices={q1:'b',q2:'d',q4:'b',q5:'b',q6:'a',q11:'c',q14:'b',q19:'a',q20:'b',q23:'c'};setAnswer(state,q.id,choices[q.id]||'a');}
 state.locked=freeze(state.answers);QUESTIONS.filter(q=>q.test).forEach((q,i)=>setAnswer(state,q.id,['c','a','a','b','d','a'][i]));state.cursor=30;state.started=true;screen='results';
}else{try{state=restore(localStorage.getItem(KEY));}catch{storageOK=false;}}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=s=>{const who=facts(state.answers).close;const person=who?`your ${who==='friend'?'close friend':who}`:'the person you have in mind';return s.replaceAll('[Your person]',person[0].toUpperCase()+person.slice(1)).replaceAll('[your person]',person);};
const btn=(name,title,cls='quiet',extra='')=>`<button class="${cls}" data-act="${name}" ${extra}>${title}</button>`;
function save(){if(previewMode)return;try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageOK=false;}}
function progress(){return QUESTIONS.filter(q=>Object.hasOwn(state.answers,q.id)).length;}
function header(){return `<header><div class="logo">genii<span>THE UNFILTERED EDITION</span></div><nav>${btn('home','Home')}${state.started?btn('evidence','Evidence'):''}${previewMode?btn('exit-preview','Back to my quiz'):state.started?btn('reset','Start fresh'):''}</nav></header>`;}
function footer(){return `<p class="foot">Local research demo · 30 authored questions · Your answers stay in this browser.<br>Rule-based evidence mapping, not a clinical assessment or a validated personality test. Written notes are saved but not scored.</p>`;}
function home(){return `<main><div class="hero"><section><span class="eyebrow">A little too specific. Potentially about you.</span><h1>You contain<br>multitudes.<br>And receipts.</h1><p>Thirty questions. A few questionable decisions. A reading that has to show its work.</p><div><span class="pill">24 getting-to-know-you questions</span><span class="pill">6 hidden-prediction checks</span><span class="pill">About 8–12 minutes</span></div><div class="actions">${btn('begin',state.started?'Continue my attempt →':'Let’s see what you’ve got →','primary')}${state.locked&&state.cursor>=30?btn('results','See my reading','secondary'):''}</div><p class="tiny muted">Pick what you would actually do. Your publicist is not answering this.</p>${btn('preview','Preview a sample result ↗')}</section><aside class="preview"><div class="face" aria-hidden="true">( ◕ ◕ )</div><span class="eyebrow">A preview of the allegations</span><blockquote>“I can afford a cameo.”</blockquote><p>One night of the group trip.<br>A whole personality in the negotiation.</p><small>We’ll check that theory against your other answers.</small></aside></div>${footer()}</main>`;}
function play(){
 if(state.cursor>=30)return result();if(state.cursor===24&&!state.locked)return checkpoint();
 const q=QUESTIONS[state.cursor];picked=state.answers[q.id]??null;
 if(q.applicable==='shared'&&facts(state.answers).household==='alone'){state.answers[q.id]='skip';state.cursor++;save();return play();}
 const test=q.test;const done=Object.hasOwn(state.answers,q.id);const disabled=test&&done;
 return `<main><div class="grid"><section><div class="counter">${test?'THE PREDICTION ROUND':'GETTING TO KNOW YOU'} <span class="muted">/ ${state.cursor+1} OF 30</span></div><div class="track" role="progressbar" aria-label="Survey progress" aria-valuemin="0" aria-valuemax="30" aria-valuenow="${state.cursor}"><i style="width:${state.cursor/30*100}%"></i></div><h1 class="qtitle" tabindex="-1">${esc(text(q.title))}</h1>${q.hint?`<p class="muted tiny">${esc(q.hint)}</p>`:''}<div class="options" role="group" aria-label="Answer choices">${q.options.map(o=>`<button class="option ${picked===o.id?'selected':''}" data-option="${o.id}" aria-pressed="${picked===o.id}" ${disabled?'disabled':''}><span class="letter">${o.id.toUpperCase()}</span><span>${esc(text(o.text))}</span></button>`).join('')}</div><details><summary>There’s context (optional)</summary><label class="tiny" for="note">Saved with this answer; not interpreted or scored.</label><textarea id="note" maxlength="1200" ${disabled?'disabled':''} placeholder="What would change your answer?">${esc(state.notes[q.id]||'')}</textarea></details><div class="actions">${state.cursor>0&&!test?btn('back','← Back','secondary'):''}${btn('next',state.cursor===29?'Show my reading →':'Continue →','primary',picked?'':'disabled')}${!disabled?btn('skip','Not applicable / skip'):''}</div>${!test?`<p class="tiny muted">Answers can be changed before the prediction round.</p>`:`<p class="tiny muted">Predictions are locked and hidden. Test answers cannot be changed in this attempt.</p>`}</section><aside class="card side"><span class="eyebrow">${test?'No peeking':'An evidence-based read'}</span><div class="railstat">${test?'06':'17'}</div><h3>${test?'Predictions committed':'Behavior & habit dimensions'}</h3><p class="tiny">${test?'Your earlier answers are frozen. These six choices will test the reading; they will not be used to build it.':'Patterns matter more than any single answer. Different relationship contexts stay separate, and missing evidence stays missing.'}</p><hr style="border:0;border-top:1px solid var(--line)"><p class="tiny muted">${storageOK?'Progress saved on this device.':'Storage unavailable. Keep this tab open; use Export to keep a copy.'}</p>${btn('export','Export this attempt ↓','secondary')}</aside></div>${footer()}</main>`;
}
function checkpoint(){return `<main style="max-width:760px"><span class="eyebrow">24 / 30 · the moment of truth</span><h1>The theory is in.<br>Let’s test it.</h1><p>Next are six new situations. Genii will lock its predictions before you answer and reveal them together at the end.</p><div class="card"><h3>What gets frozen?</h3><p>Your first 24 answers and their evidence map. The final six never feed back into that reading.</p><p class="tiny muted">If the evidence is too thin or tied, Genii will abstain. We’ll compare its picks with a fixed answer set that does not use your profile. Six checks are a small experiment, not proof of accuracy. For an unfamiliar-situation test, the respondent must not have seen these questions before.</p></div><div class="actions">${btn('lock','Lock predictions & continue →','primary')}${btn('evidence','Review my answers','secondary')}</div>${footer()}</main>`;}
function evidenceCards(groups){return groups.map(g=>`<article class="card"><span class="status">${esc(g.status)}</span><h3 style="margin-top:15px">${esc(DIMS[g.d])}</h3><p class="tiny muted">${esc(g.d)} · ${esc(g.target)} · ${g.n} observation${g.n===1?'':'s'}</p><p>${g.top?esc(label(g.top)):'No single pattern leads.'}${g.mixed?' <span class="muted">Other choices point another way.</span>':''}</p><details><summary>Show the evidence</summary>${g.rows.map(r=>`<div class="evidence"><b>${r.question.toUpperCase()} · ${esc(label(r.v))}${r.role==='actual'?' · reported real experience':''}</b><q>${esc(text(r.answer))}</q><span>${esc(r.why)}</span></div>`).join('')}</details></article>`).join('');}
function result(){
 const groups=state.locked?.profile||profile(state.answers),f=state.locked?.facts||facts(state.answers),id=identity(groups),s=stats(state);
 const covered=new Set(groups.map(g=>g.d));if(f.bedtime)covered.add('D14a');if(f.takeaway)covered.add('D14b');if(f.movement)covered.add('D14c');
 const candidates=groups.filter(g=>g.n>=2&&g.top&&g.status==='Repeated pattern').sort((a,b)=>b.n-a.n);const featured=[];for(const g of candidates){if(!featured.some(x=>x.d===g.d)&&featured.length<3)featured.push(g);}
 const context=t=>t==='general'?'Across these situations':t==='friend'?'With friends in group situations':t.startsWith('chosen ')?`With your ${t}`:`Context: ${t}`;
 const initials=id.title.replace(/^The /,'').split(' ').filter(Boolean).map(w=>w[0]).slice(0,2).join('');
 const factLabels={close:'Your recurring person',household:'Who you live with',bedtime:'Usual bedtime',takeaway:'Restaurant / takeaway dinners',movement:'Exercise days'};
 return `<main class="reading"><section class="reveal"><div class="reveal-copy"><span class="edition"><i aria-hidden="true">✧</i> YOUR GENII, DECODED</span><p class="reveal-kicker">Well. This feels familiar.</p><h1 tabindex="-1">${esc(id.title.replace(/^The /,''))}<span class="title-period">.</span></h1><p class="reading-line">${esc(id.line)}</p><div class="reading-tags">${featured.map(g=>`<span>${esc(label(g.top))}</span>`).join('')||'<span>Still a little mysterious</span>'}</div><div class="actions">${btn('save-card','Save my result card ↗','primary reveal-button')}${btn('jump-patterns','Explore my reading ↓','quiet')}</div><p class="reveal-note">A playful interpretation of your choices. Room for nuance included.</p><p id="card-status" class="tiny" role="status"></p></div><div class="card-stage"><div class="orbit orbit-one" aria-hidden="true"></div><div class="orbit orbit-two" aria-hidden="true"></div><article class="collectible" aria-label="Your collectible result card"><div class="collector-top"><b>genii</b><span>THE UNFILTERED EDITION</span></div><div class="rosette" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><span>${esc(initials)}</span></div><div class="collector-label">A FAMILIAR KIND OF STRANGE</div><h2>${esc(id.title)}</h2><div class="collector-foot"><span>${previewMode?'SAMPLE READING':'YOUR PERSONALITY SNAPSHOT'}</span><span aria-hidden="true">✦</span></div></article><span class="card-caption">A little souvenir of being perceived.</span></div></section>
 <section class="patterns-section" id="patterns"><div class="section-heading"><div><span class="eyebrow">THE PART WHERE IT GETS SPECIFIC</span><h2>There’s a pattern here.</h2></div><p>These choices showed up more than once.<br>Tap a receipt to see where they came from.</p></div><div class="pattern-grid">${featured.map((g,i)=>`<article class="pattern-card tone-${i}"><span class="pattern-glyph" aria-hidden="true">${['↗','◎','✳'][i]}</span><span class="eyebrow">${esc(DIMS[g.d])}</span><h3>${esc(label(g.top))}</h3><p class="pattern-context">${esc(context(g.target))}</p><p>${esc(g.rows.find(r=>r.v===g.top).why)}</p><details><summary>${g.n} observations · view receipts <span aria-hidden="true">↗</span></summary>${g.rows.map(r=>`<div class="evidence"><b>${r.question.toUpperCase()} · ${esc(label(r.v))}</b><q>${esc(text(r.answer))}</q><span>${esc(r.why)}</span></div>`).join('')}</details></article>`).join('')||'<article class="pattern-card empty-pattern"><h3>We’re keeping the mystery.</h3><p>There isn’t enough repeated evidence for a strong pattern yet. You can inspect the observations below or revisit your answers.</p></article>'}</div></section>
 ${s?`<section class="prediction-recap"><div class="recap-intro"><span class="eyebrow">THE RECEIPTS, PLEASE</span><h2>Did the reading <br>predict you?</h2><p>Six new situations.<br>The guesses were locked first.</p></div><div class="recap-body"><div class="recap-scores"><div><strong>${s.hits}<span> / ${s.predicted}</span></strong><p>Genii matched</p></div><div><strong>${s.baselineHits}<span> / ${s.predicted}</span></strong><p>Fixed baseline matched</p></div></div><div class="check-strip" aria-label="Six prediction outcomes">${s.trials.map((t,i)=>{const type=t.skipped?'skipped':!t.option?'abstained':t.hit?'matched':'missed';return `<div class="check-tile ${type}"><span class="check-number">Q${25+i}</span><b aria-hidden="true">${({matched:'✓',missed:'×',abstained:'—',skipped:'·'})[type]}</b><span>${type}</span></div>`;}).join('')}</div><p class="score-caption">${s.predicted} scored predictions · ${s.abstained} abstentions · ${s.skipped} skipped${s.predicted===0?' · Not enough predictions to calculate a match rate.':''}</p><details class="prediction-details"><summary>Open the prediction breakdown <span aria-hidden="true">↗</span></summary>${s.trials.map(t=>{const q=QUESTIONS.find(q=>q.id===t.question),name=v=>q.options.find(o=>o.id===v)?.text;return `<div class="testrow"><strong>${esc(text(q.title))}</strong><p class="tiny">Genii: ${esc(name(t.option)||'Abstained')}<br>You: ${esc(name(t.actual)||'Skipped')}<br>Baseline: ${esc(name(t.baseline))}</p><small>${esc(t.reason)} · Earlier evidence: ${t.sources.map(x=>x.toUpperCase()).join(', ')||'none'}</small></div>`;}).join('')}<p class="tiny">Fixed baseline across all ${s.answered} answered checks: ${s.baselineAll}/${s.answered}. The headline comparison uses the same scored subset for both.</p></details></div></section>`:''}
 <section class="reading-depth"><div class="section-heading"><div><span class="eyebrow">MORE YOU, LESS GUESSWORK</span><h2>There’s more to the story.</h2></div><p>Everything behind the headline.<br>Nothing quietly swept under the rug.</p></div><details class="depth-panel"><summary><span><b>Your full evidence map</b><small>Repeated, mixed, and thin evidence — all included</small></span><span class="expand-icon" aria-hidden="true">+</span></summary><div class="depth-content"><p class="tiny muted">${covered.size}/17 dimensions have an observation or a direct habit fact. Coverage is not confidence. One observation stays “thin”.</p><div class="resultgrid">${evidenceCards(groups)||'<p>No behavioral evidence recorded.</p>'}</div></div></details>
 <details class="depth-panel"><summary><span><b>What you told us directly</b><small>Your context and habits, separate from our interpretation</small></span><span class="expand-icon" aria-hidden="true">+</span></summary><div class="depth-content">${Object.entries(f).map(([k,v])=>`<div class="fact"><b>${esc(factLabels[k]||k)}</b><span>${esc(v)}</span></div>`).join('')||'<p>No context facts supplied.</p>'}<p class="tiny muted">Self-reported facts are not successful guesses. Meal frequency does not establish nutritional quality.</p></div></details>
 <details class="depth-panel"><summary><span><b>Where the reading stops</b><small>Gaps, uncertainty, and how this demo works</small></span><span class="expand-icon" aria-hidden="true">+</span></summary><div class="depth-content"><p>Unobserved dimensions: ${Object.keys(DIMS).filter(d=>!covered.has(d)).map(d=>`${d} ${DIMS[d]}`).join(', ')||'None, though some evidence may still be thin.'}</p><p>Different answers can reflect different circumstances, not dishonesty. This short demo does not meet the full survey’s repeated-measure coverage requirements. The headline is a playful summary, not a fixed personality type.</p><p>Choices map to authored categories. Predictions compare patterns in matching relationship contexts and abstain when support is too thin or tied. Written notes are saved but not scored.</p><p>Six checks and a fixed, non-population baseline are an experiment, not validated accuracy. Starting fresh cannot make these scenarios unfamiliar again.${state.reviewed?' This attempt followed earlier exposure to the test material.':''}</p></div></details></section>
 <section class="reading-outro"><span aria-hidden="true">✧</span><h2>You’re more than a result.<br><em>But this is a pretty good conversation starter.</em></h2><div class="actions">${btn('save-card','Save my result card ↗','primary')}${btn('evidence','Inspect my answers','secondary')}${btn('export','Download private evidence ↓','quiet')}</div><p class="tiny muted">Your result card contains the playful headline only. Answers and relationship details stay out.</p></section>${footer()}</main>`;
}
function downloadCard(){
 const id=identity(state.locked?.profile||profile(state.answers));const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const c=canvas.getContext('2d');if(!c)return;
 const bg=c.createLinearGradient(0,0,1080,1350);bg.addColorStop(0,'#e9e3fb');bg.addColorStop(.65,'#f5d2c1');bg.addColorStop(1,'#f2edb0');c.fillStyle=bg;c.fillRect(0,0,1080,1350);
 c.fillStyle='#28253d';c.font='bold 48px sans-serif';c.fillText('genii',82,106);c.font='18px sans-serif';c.fillText(previewMode?'SAMPLE READING':'THE UNFILTERED EDITION',82,151);
 c.save();c.translate(540,490);for(let i=0;i<12;i++){c.rotate(Math.PI/6);c.beginPath();c.ellipse(0,0,245,90,0,0,Math.PI*2);c.strokeStyle='rgba(104,84,189,.24)';c.lineWidth=2;c.stroke();}c.restore();
 c.textAlign='center';c.font='italic 70px Georgia';c.fillText('A familiar kind',540,485);c.fillText('of strange.',540,565);c.font='18px sans-serif';c.fillText('YOUR GENII READING',540,835);
 c.font='64px Georgia';let line='',y=930;for(const word of id.title.split(' ')){const next=line?line+' '+word:word;if(c.measureText(next).width>900){c.fillText(line,540,y);y+=78;line=word;}else line=next;}c.fillText(line,540,y);
 c.font='21px sans-serif';c.fillText('A playful snapshot. Not the whole story.',540,1235);
 canvas.toBlob(blob=>{const status=document.getElementById('card-status');if(!blob){if(status)status.textContent='Could not create the card. Please try again.';return;}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=previewMode?'genii-sample-card.png':'my-genii-card.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);if(status)status.textContent='Your card is ready. Only the headline is included.';},'image/png');
}
function inspect(){const rows=evidence(state.answers);return `<main>${btn('return','← Return','quiet backlink')}<span class="eyebrow">The receipts</span><h1>Nothing up our sleeve.</h1><p>See the answer, the mapping, and what remains uncertain. Changing an earlier answer clears the six checks so old results cannot masquerade as a new prediction.</p>${QUESTIONS.filter(q=>!q.test).map((q,i)=>{const a=selected(q,state.answers);return `<article class="listrow"><span class="counter">${i+1} / 24</span><h3>${esc(text(q.title))}</h3><p>${esc(a?text(a.text):state.answers[q.id]==='skip'?'Skipped':'Not answered')}</p><p class="tiny muted">${esc(a?.why||'No evidence recorded.')}</p><div class="badges">${rows.filter(r=>r.question===q.id).map(r=>`<span class="pill">${esc(r.d)} · ${esc(label(r.v))} · ${esc(r.target)}</span>`).join('')}</div>${state.notes[q.id]?`<p class="tiny">Unscored note: ${esc(state.notes[q.id])}</p>`:''}${btn('edit','Edit answer','secondary',`data-index="${i}"`)}</article>`;}).join('')}${footer()}</main>`;}
function render(){document.body.dataset.view=(screen==='results'||screen==='play'&&state.cursor>=30)?'reading':screen;root.innerHTML=header()+(previewMode?'<div class="sample-banner"><b>Sample reading</b> · Fictional answers. Your saved progress is untouched.</div>':'')+(!storageOK?'<div class="notice warning" role="status">Browser storage is unavailable. Keep this tab open or export your attempt.</div>':'')+(screen==='home'?home():screen==='evidence'?inspect():screen==='results'?result():play());}
function focusTitle(){root.querySelector('main h1')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
function advance(value){const q=QUESTIONS[state.cursor];if(!q)return;const note=root.querySelector('#note')?.value;if(note!==undefined)state.notes[q.id]=note;
 if(!q.test&&state.locked&&QUESTIONS.some(x=>x.test&&Object.hasOwn(state.answers,x.id)))state.reviewed=true;
 setAnswer(state,q.id,value);
 state.cursor++;save();render();focusTitle();}
function exportAttempt(){const out={version:VERSION,sample:previewMode,method:'Authored categorical parser; free text is unscored; local prototype',...state,evidence:evidence(state.answers),facts:facts(state.answers),profile:state.locked?.profile||profile(state.answers),test:stats(state)};if(state.cursor<30){out.locked=state.locked?{version:state.locked.version,signature:state.locked.signature,predictions:'Hidden until all six checks are finished'}:null;out.test=null;}const url=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='genii-private-attempt.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
root.addEventListener('click',e=>{
 const option=e.target.closest('[data-option]');if(option){picked=option.dataset.option;root.querySelectorAll('[data-option]').forEach(b=>{b.classList.toggle('selected',b.dataset.option===picked);b.setAttribute('aria-pressed',b.dataset.option===picked);});root.querySelector('[data-act="next"]').disabled=false;return;}
 const button=e.target.closest('[data-act]');if(!button)return;const action=button.dataset.act;
 if(action==='preview'){location.search='?preview=result';return;}
 if(action==='exit-preview'){location.search='';return;}
 if(action==='save-card'){downloadCard();return;}
 if(action==='jump-patterns'){document.getElementById('patterns')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});return;}
 if(action==='export'){exportAttempt();return;}
 if(action==='reset'){if(!confirm('Delete this browser’s answers and start a new attempt? Export first if you want to keep them.'))return;state=fresh();screen='home';save();render();return;}
 if(action==='home')screen='home';
 if(action==='begin'){state.started=true;screen=state.cursor>=30?'results':'play';}
 if(action==='results')screen='results';
 if(action==='evidence'){backScreen=screen;screen='evidence';}
 if(action==='return')screen=backScreen;
 if(action==='edit'){state.cursor=Number(button.dataset.index);screen='play';}
 if(action==='back'){state.cursor=Math.max(0,state.cursor-1);if(state.cursor===14&&facts(state.answers).household==='alone')state.cursor--;}
 if(action==='next'){if(picked===null)return;if(QUESTIONS[state.cursor]?.test&&Object.hasOwn(state.answers,QUESTIONS[state.cursor].id)){state.cursor++;}else{advance(picked);return;}}
 if(action==='skip'){advance('skip');return;}
 if(action==='lock'){const ready=QUESTIONS.filter(q=>!q.test).every(q=>Object.hasOwn(state.answers,q.id));if(!ready){state.cursor=QUESTIONS.findIndex(q=>!q.test&&!Object.hasOwn(state.answers,q.id));screen='play';}else{state.locked=freeze(state.answers);state.testSeen=true;state.cursor=24;screen='play';}}
 save();render();focusTitle();
});
root.addEventListener('input',e=>{if(e.target.id==='note'){state.notes[QUESTIONS[state.cursor].id]=e.target.value;save();}});
render();
