export const VERSION='genii-evidence-30.v1';
export const DIMS={D1:'First move',D2:'Risk & novelty',D3:'Planning',D4:'Money motive',D5:'Closeness worry',D6:'Closeness distance',D7:'Conflict style',D8:'Fairness & effort',D9:'Recognition & rivalry',D10:'Mood-driven urgency',D11:'Duty & autonomy',D12:'Repair after mistakes',D13:'Care & its limits',D14a:'Sleep rhythm',D14b:'Eating habits',D14c:'Movement',D14d:'Recovery'};
const o=(text,tags='',why='',facts={})=>({text,tags:tags?tags.split(' ').map(t=>{const [pair,target='general']=t.split('@');const [d,v]=pair.split(':');return {d,v,target};}):[],why,facts});
const q=(id,title,options,extra={})=>({id:`q${id}`,title,options:options.map((x,i)=>({...x,id:String.fromCharCode(97+i)})),...extra});
export const QUESTIONS=[
q(1,'Before we start: who gets the unfiltered version of you?',[
o('My partner. They have seen the extended cut.','','You explicitly chose a partner as the recurring relationship target.',{close:'partner'}),o('A close friend. Unfortunately, they know the lore.','','You explicitly chose a close friend.',{close:'friend'}),o('My mum. There is no deleting that chat history.','','You explicitly chose your mother.',{close:'mother'}),o('My dad. An unexpected but strong contender.','','You explicitly chose your father.',{close:'father'}),o('Someone else I trust. Their identity is not essential to the plot.','','You chose another trusted person; no relationship status is inferred.',{close:'trusted person'})],{kind:'context',hint:'This person will appear as [your person] later. Pick one relationship to explore.'}),
q(2,'Who lives with you and your collection of slightly useful cables?',[
o('Just me. Every mysterious noise is my problem.','','Self-reported living arrangement.',{household:'alone'}),o('Family. Privacy is more of a suggestion.','','Self-reported living arrangement.',{household:'family'}),o('A partner. We own at least one object neither of us likes.','','Self-reported living arrangement.',{household:'partner'}),o('Roommates. There are ongoing negotiations over a sponge.','','Self-reported living arrangement.',{household:'roommates'}),o('A mix, or something else. It requires a diagram.','','No specific household structure is inferred.',{household:'other'})],{kind:'context',hint:'Choose the closest fit. You can explain a mixed arrangement in the optional note.'}),
q(3,'The group chat says “cheap little trip” and sends a villa with a helipad. It is over your budget. What do you say?',[
o('“Can we go somewhere that knows what a coupon is?”','D4:security D3:plan D7:direct@friend','You propose an affordable alternative and state the constraint.'),o('“I’m in.” Future me will be furious.','','You accept a known budget overrun for this experience; the reason is not established.'),o('“I’ll come for one night. I can afford a cameo.”','D4:security D3:plan','You limit participation to control the cost.'),o('“Can’t, I’m busy.” Busy not being able to afford that.','D4:security D7:avoid@friend','You protect your budget while concealing the reason from friends.')]),
q(4,'Bad day. Full cart. Apparently the missing piece of your life is a tiny lamp shaped like a duck. What now?',[
o('Buy it. I have never been sad with this particular duck.','D10:act D3:improvise','You make an immediate purchase after a bad day.'),o('Sleep on it. He will still be a duck tomorrow.','D10:wait D3:plan','You delay the decision rather than buying immediately.'),o('Read the reviews. Has he disappointed other people?','D3:plan','You gather information; we cannot tell whether you ultimately buy.'),o('Close the app. My feelings can remain unlit.','D10:wait','You decline this mood-related purchase.')]),
q(5,'A friend has a spare ticket to something you have never tried. You have the time and money. How much information do you need?',[
o('None. I’m putting my shoes on.','D2:novel D3:improvise','You accept a novel experience without investigating.'),o('A quick look at what it involves. Even a side quest needs a description.','D2:conditional D3:plan','You investigate before committing.'),o('I suggest something we already know we like. Why interrupt a winning streak?','D2:familiar','You prefer a familiar alternative with practical constraints removed.'),o('I’ll try it if another friend comes. We can be confused together.','D2:conditional','Your willingness depends on having familiar company.')]),
q(6,'[Your person] has not replied in six hours, but their sandwich just got a three-part story. What happens in your head first?',[
o('They’re probably busy. The sandwich and I can coexist.','D5:secure@close','You describe a benign interpretation of the delay.'),o('I worry something happened and send a check-in. Even sandwich people need checking on.','D6:support@close','You seek contact out of stated concern for their safety, not inferred insecurity.'),o('I reread my message. Maybe “haha” was too much.','D5:reassurance@close','You question your own message in response to silence.'),o('I’m annoyed and want to ask why they haven’t replied. The bread can wait.','D7:direct@close','You want a direct explanation; annoyance is not scored as attachment anxiety.')]),
q(7,'You argued with [your person] yesterday. Today they send a raccoon eating grapes. No explanation. Just grapes. You…',[
o('“He’s incredible. Can we talk about yesterday?”','D7:direct@close D12:repair@close','You maintain contact and explicitly reopen repair.'),o('Send one back, then ask to talk tonight. The raccoons get the afternoon off.','D7:soften@close D12:repair@close','You soften the opening and arrange a conversation.'),o('Send one back and leave it there. Apparently the grapes worked.','D7:avoid@close','You resume contact without addressing the disagreement.'),o('Say I need a day before we talk. I’m not ready, even for this raccoon.','D7:pause@close D6:private@close','You explicitly request space; that is not punitive silence.')]),
q(8,'A relative gives your life choices a one-star review over dinner. Nobody asked. What do you do?',[
o('“I’m happy with my choice.” Pass the potatoes.','D11:autonomy D7:direct@relative','You state autonomy directly to a relative; no specific parent is inferred.'),o('Explain the plan so they understand. My dinner now comes with a presentation.','D7:direct@relative D3:plan','You explain your reasoning; approval-seeking is not assumed.'),o('Make a joke and change the subject. The fish is getting cold and so am I.','D7:avoid@relative','You redirect the discussion.'),o('Reconsider it seriously. Their opinion matters to me, even with terrible delivery.','D11:duty','You give family expectations a role in reconsidering your choice.')]),
q(9,'You ordered fries. Everyone else ate the aquarium. Someone suggests splitting the bill evenly.',[
o('“I’ll cover mine.” I did not sponsor that lobster.','D8:proportional@friend D7:direct@friend','You directly request a consumption-based split.'),o('Split it. I’ll pay a little extra to avoid doing maths in public.','D8:absorb@friend D4:convenience','You accept extra cost for convenience.'),o('Quietly ask to pay for mine. I want my money, not a scene.','D8:proportional@friend D7:soften@friend','You privately request a consumption-based split.'),o('Pay, say nothing, remember the lobster’s full name.','D8:absorb@friend D7:hint@friend','You absorb the cost with unexpressed resentment.')]),
q(10,'A teammate presents your joint work and says “I” so often that “we” should file a missing-person report. First move?',[
o('Mention what I contributed, right there. Just fixing the credits.','D7:direct@colleague D8:proportional@colleague','You publicly clarify your contribution.'),o('Speak to them afterward. No audience required.','D7:soften@colleague','You address it privately.'),o('Send the lead a record of the work. My screenshots have been training for this.','D3:plan D8:proportional@colleague','You use documented evidence to seek accurate attribution.'),o('Leave it this time; keep a clearer record next time. The sequel has receipts.','D7:avoid@colleague D3:plan','You defer confrontation and plan future documentation.')],{hint:'Think work, school, volunteering, or another shared project.'}),
q(11,'Your friend gets the opportunity you wanted. You are happy for them. Your ego would prefer to lie face down. First move?',[
o('Call to celebrate. I can have my floor moment later.','D9:noncompetitive D6:support@friend','You prioritize connection despite disappointment in this instance.'),o('Congratulate them, then mute updates briefly. I cannot watch the montage yet.','D6:private@friend D9:comparison','You limit exposure to a painful comparison while expressing support.'),o('Ask how they did it and make a plan. Jealousy has made me productive.','D9:competitive D3:plan','You use comparison to motivate action.'),o('Wait until I can reply warmly. The first draft has teeth.','D10:wait','You delay your response while emotions settle.')]),
q(12,'You forgot something important to [your person]. They say “it’s fine.” The full stop suggests otherwise. What next?',[
o('Apologize and ask how to make it right. No “but” trying to sneak in.','D12:repair@close D7:direct@close','You explicitly own the mistake and ask about repair.'),o('Apologize and explain what happened. Context, not an escape tunnel.','D12:explain@close','You combine an apology with an explanation; this is not scored as blame-shifting.'),o('Arrange something thoughtful to make up for it. This apology has snacks.','D12:action@close D3:plan','You initiate a concrete gesture of repair.'),o('Ask if they need space, then agree when to talk. Quiet, not vanished.','D12:pause@close D7:pause@close','You coordinate a pause with a plan to reconnect.')]),
q(13,'A soaked stray cat looks at you like you personally control the weather. You cannot take it home. First move?',[
o('Bring food and water. I offer catering, not accommodation.','D13:direct D1:people','You provide immediate care within a stated limit.'),o('Contact a rescue. We need someone with cat capacity.','D13:coordinate D3:plan','You seek organized help.'),o('Ask nearby people who can help. Congratulations, we’re a committee.','D13:coordinate D1:people','You mobilize others to help.'),o('I cannot safely help right now, so I leave.','D13:limit D1:self','You state a situational safety or capacity limit, not dislike of animals.')]),
q(14,'You are exhausted. A stranger asks for help finding their stop. Your own bus is arriving. What do you do?',[
o('Stay and help them figure it out. My bus and I will meet again.','D13:direct D1:people','You accept a personal cost to provide direct help.'),o('Give quick directions, then catch my bus. Helpful, with a departure time.','D13:bounded D14d:rest','You provide limited help while protecting your own capacity.'),o('Point them to a staff member before I go. Passing the baton, not the problem.','D13:coordinate','You connect them with another source of help.'),o('Apologize and catch my bus. I have no spare battery today.','D13:limit D14d:rest','You prioritize your current capacity in this scenario.')]),
q(15,'The people you live with think the house cleans itself. You are the house. What happens next?',[
o('Tell them we need to split the chores. I was not included with the furniture.','D8:proportional@household D7:direct@household','You explicitly renegotiate the division of labor.'),o('Make a rota. The bin apparently needs a custody agreement.','D8:proportional@household D3:plan','You organize an explicit division of labor.'),o('Do it myself. Washing the dish is less effort than discussing the dish.','D8:absorb@household D7:avoid@household','You absorb labor to avoid a discussion.'),o('Stop doing their share. Let’s see how magical this house really is.','D8:proportional@household','You stop covering others; whether you explain this is unknown.')],{applicable:'shared',hint:'If you live alone or this situation does not fit, use “Not applicable”.'}),
q(16,'What time do you usually stop being available to consciousness?',[
o('Before 11 p.m. Tomorrow me has excellent representation.','','Self-reported usual bedtime; not a health judgment.',{bedtime:'before 23:00'}),o('Between 11 p.m. and 1 a.m. A reasonable amount of one more episode.','','Self-reported usual bedtime.',{bedtime:'23:00–01:00'}),o('After 1 a.m. The internet becomes very important at midnight.','','Self-reported usual bedtime.',{bedtime:'after 01:00'}),o('It varies or I work shifts. Time and I have an arrangement.','','Self-reported variable schedule; no inference of poor discipline.',{bedtime:'variable / shifts'})],{kind:'fact',dimension:'D14a'}),
q(17,'In the last seven days, how many dinners arrived from a restaurant or takeaway? We are counting meals, not judging them.',[
o('None. The kitchen has proof of life.','','Self-reported dinner frequency, not nutritional quality.',{takeaway:'0 days / last 7'}),o('One or two. The delivery app knows me casually.','','Self-reported dinner frequency.',{takeaway:'1–2 days / last 7'}),o('Three or four. We are becoming close.','','Self-reported dinner frequency.',{takeaway:'3–4 days / last 7'}),o('Five to seven. The doorbell is my dinner bell.','','Self-reported dinner frequency.',{takeaway:'5–7 days / last 7'})],{kind:'fact',dimension:'D14b'}),
q(18,'In the last seven days, on how many days did you deliberately get some exercise? Searching for your charger does not count.',[
o('Zero. A factual answer, not a confession.','','Self-reported movement frequency; no fitness inference.',{movement:'0 days / last 7'}),o('One or two. There was movement. Witnesses exist.','','Self-reported movement frequency.',{movement:'1–2 days / last 7'}),o('Three or four. A recurring event.','','Self-reported movement frequency.',{movement:'3–4 days / last 7'}),o('Five to seven. My calendar has trainers on.','','Self-reported movement frequency.',{movement:'5–7 days / last 7'})],{kind:'fact',dimension:'D14c',hint:'Include walks, wheelchair exercise, or movement that works for your body.'}),
q(19,'It is 11 p.m. after a cursed day. What do you reach for first?',[
o('Bed. I would like to unsubscribe from today.','D14d:rest D10:wait','You choose sleep as immediate recovery in this scenario.'),o('A call with [your person]. I need a witness, not a solution.','D6:support@close','You seek support from the selected person.'),o('My phone. “Ten minutes,” says a known liar.','D10:act','You choose an immediate distraction; usual sleep duration remains unknown.'),o('Finish one more task. Rest will feel better if the thing is done.','D14d:obligation D1:task','You prioritize finishing an obligation over immediate rest.')]),
q(20,'You are trying to cut back on late-night scrolling. Tonight your brain says “just this once,” despite its extensive criminal record.',[
o('Keep scrolling. Tomorrow me can be inspirational.','D10:act','You choose immediate relief over the stated intention tonight.'),o('Put the phone in another room. Distance makes the thumb less stupid.','D3:plan D10:wait','You change your environment to delay the habit.'),o('Ask [your person] to keep me company while I put it away.','D6:support@close D3:plan','You seek practical support and an alternative activity.'),o('Set a short timer, then stop. A negotiated surrender.','D3:plan D10:wait','You propose a bounded plan; actual follow-through is not established.')]),
q(21,'A pricey self-care purchase catches your eye. Your future self looks incredible in the advert. How do you decide?',[
o('Check whether I will use it and whether it fits my budget. Future me has lied before.','D3:plan D4:security','You prioritize likely use and affordability.'),o('Buy it if I can afford it and it will make daily life nicer. Joy is allowed a line in the budget.','D4:enjoyment','You prioritize enjoyment within your stated means.'),o('Find a cheaper version that does the job. Same face, smaller invoice.','D3:plan D4:security','You compare functional value and price.'),o('Buy the recognizable brand because I like being seen with it. At least I’m honest.','D4:status D9:recognition','You explicitly identify public recognition as part of the appeal.')]),
q(22,'A plan important to you falls apart. Who hears about it first?',[
o('[Your person], straight away. They get the unedited version.','D6:support@close','You promptly disclose a setback to the selected person.'),o('[Your person], once I have figured out my next move. The trailer comes after editing.','D6:private@close D3:plan','You delay disclosure until you have a plan.'),o('Someone outside the situation. I want a fresh set of ears.','D6:selective@general','You seek support elsewhere; no assumption is made about the chosen relationship.'),o('Nobody yet. I need to make sense of it on my own.','D6:private@close','You initially process the setback privately.')]),
q(23,'You are exhausted, an important deadline is tomorrow, and a friend wants help with something that can wait. What happens first?',[
o('Help my friend. I find it hard to leave someone hanging.','D1:people D14d:obligation','You prioritize the other person over immediate rest and your task.'),o('Finish my deadline. Then I can be a person again.','D1:task D14d:obligation','You prioritize the immediate task over rest.'),o('Rest, then make a plan for both. I am no use as a haunted lampshade.','D1:self D14d:rest D3:plan','You protect recovery before organizing the obligations.'),o('Tell my friend when I can help and do a small part of my task. A manageable amount of being alive.','D1:task D3:plan','You communicate a limit and break down the task.')]),
q(24,'Reality check: the last time you disagreed with [your person], what did you actually do?',[
o('Said what was bothering me. The words left my mouth and everything.','D7:direct@close','You report a direct response in a recent real disagreement.'),o('Eased into it gently. A soft launch for a difficult conversation.','D7:soften@close','You report a softened opening in a recent disagreement.'),o('Asked for time, then came back to talk. Paused, not cancelled.','D7:pause@close','You report an explicit pause and return.'),o('Avoided the conversation. We moved on without dealing with it.','D7:avoid@close','You report leaving the disagreement unaddressed.')],{role:'actual',hint:'If you cannot remember or this has not happened, skip. We will not invent an example.'}),
q(25,'A new hobby looks fun. The starter kit costs more than you expected, and you have had a rough week. What do you do?',[
o('Buy the full kit tonight. I may be a completely different person by Tuesday.','D3:improvise D10:act'),o('Wait a day, check reviews, and price a basic kit. Tuesday can wait.','D3:plan D10:wait'),o('Try a cheap introductory session first. My new personality gets a trial period.','D3:plan D4:security'),o('Choose a hobby I already know I like. My cupboard has enough abandoned potential.','D2:familiar')],{test:true,baseline:'b'}),
q(26,'[Your person] cancels a plan that mattered to you, then suggests a new one without mentioning it. Your response?',[
o('“Let’s rebook, but I want to explain why I was upset.”','D7:direct@close'),o('Start warmly, then gently bring up how the cancellation felt.','D7:soften@close'),o('Say I need a day, then arrange a time to talk.','D7:pause@close'),o('Accept the new plan and leave the cancellation unmentioned.','D7:avoid@close')],{test:true,baseline:'a'}),
q(27,'Friends want to split the cost of a gift. You already paid for the wrapping and delivery. What now?',[
o('Mention what I paid and ask to include it in the split.','D8:proportional@friend D7:direct@friend'),o('Send the organizer a quiet message asking to adjust my share.','D8:proportional@friend D7:soften@friend'),o('Cover the extra. It is worth it to keep things simple.','D8:absorb@friend D4:convenience'),o('Pay the requested amount and feel annoyed without saying why.','D8:absorb@friend D7:hint@friend')],{test:true,baseline:'a'}),
q(28,'You have a free afternoon and enough money for either activity: a familiar favorite or a new experience. How do you choose?',[
o('Pick the new experience without looking it up.','D2:novel D3:improvise'),o('Look up the new option before deciding.','D2:conditional D3:plan'),o('Go with my familiar favorite.','D2:familiar'),o('Try the new one only if a friend joins me.','D2:conditional')],{test:true,baseline:'b'}),
q(29,'An optional extra task would help your team, but you are already exhausted. What do you do?',[
o('Decline and rest. I have hit my limit.','D14d:rest D1:self'),o('Take it on. I want to finish what the team needs.','D14d:obligation D1:task'),o('Find someone with capacity to share the task.','D3:plan D13:coordinate'),o('Offer a smaller contribution and protect the rest of my evening.','D3:plan D14d:rest')],{test:true,baseline:'d'}),
q(30,'You accidentally let [your person] down again, in a different situation. How do you start putting it right?',[
o('Apologize directly and ask what would help.','D12:repair@close'),o('Apologize and explain what led to it.','D12:explain@close'),o('Arrange a thoughtful, concrete way to make up for it.','D12:action@close'),o('Agree on some space and a time to reconnect.','D12:pause@close')],{test:true,baseline:'a'})
];
