import test from 'node:test';import assert from 'node:assert/strict';
import {QUESTIONS,DIMS} from './data.js';import {fresh,setAnswer,evidence,profile,freeze,stats,restore,signature,predict,identity} from './engine.js';
const filled=()=>{const s=fresh();for(const q of QUESTIONS.filter(q=>!q.test))setAnswer(s,q.id,q.options[0].id);return s;};
test('30 unique questions, 24 training and six heldouts; all mappings valid',()=>{assert.equal(QUESTIONS.length,30);assert.equal(new Set(QUESTIONS.map(q=>q.id)).size,30);assert.equal(QUESTIONS.filter(q=>q.test).length,6);for(const q of QUESTIONS){assert.ok(q.title.length);assert.ok(q.options.length>=4);for(const o of q.options)for(const t of o.tags)assert.ok(DIMS[t.d]);if(q.test)assert.ok(q.options.some(o=>o.id===q.baseline));}});
test('skips produce no profile; single observations remain thin',()=>{const s=fresh();QUESTIONS.filter(q=>!q.test).forEach(q=>setAnswer(s,q.id,'skip'));assert.deepEqual(evidence(s.answers),[]);assert.ok(freeze(s.answers).predictions.every(p=>p.option===null));setAnswer(s,'q8','a');assert.ok(profile(s.answers).every(g=>g.status==='Thin evidence'));});
test('targets stay separate; actual experiences are traceable',()=>{const s=filled();setAnswer(s,'q1','c');const rows=evidence(s.answers);assert.ok(rows.some(r=>r.target==='chosen mother'));assert.ok(rows.some(r=>r.target==='friend'));assert.ok(rows.some(r=>r.target==='relative'));assert.ok(rows.some(r=>r.role==='actual'&&r.question==='q24'));});
test('holdout answers never change frozen evidence or predictions',()=>{const s=filled();s.locked=freeze(s.answers);const before=JSON.stringify(s.locked),rows=JSON.stringify(evidence(s.answers));for(const q of QUESTIONS.filter(q=>q.test))setAnswer(s,q.id,'d');assert.equal(JSON.stringify(s.locked),before);assert.equal(JSON.stringify(evidence(s.answers)),rows);assert.equal(stats(s).answered,6);assert.throws(()=>setAnswer(s,'q25','a'));});
test('training edit clears every test and snapshot',()=>{const s=filled();s.locked=freeze(s.answers);setAnswer(s,'q25','a');setAnswer(s,'q4','b');assert.equal(s.locked,null);assert.equal(s.answers.q25,undefined);});
test('all-skipped tests have no fake denominator or score',()=>{const s=filled();s.locked=freeze(s.answers);QUESTIONS.filter(q=>q.test).forEach(q=>setAnswer(s,q.id,'skip'));const a=stats(s);assert.equal(a.answered,0);assert.equal(a.predicted,0);assert.equal(a.skipped,6);});
test('restore rejects stale snapshot and reconstructs untrusted prediction data',()=>{const s=filled();s.locked=freeze(s.answers);s.locked.predictions[0].option='fake';const r=restore(JSON.stringify(s));assert.notEqual(r.locked.predictions[0].option,'fake');s.answers.q3='b';assert.equal(restore(JSON.stringify(s)).locked,null);assert.deepEqual(restore('broken'),fresh());});
test('changing to solo household removes incompatible evidence',()=>{const s=filled();setAnswer(s,'q2','d');setAnswer(s,'q15','a');assert.ok(evidence(s.answers).some(r=>r.question==='q15'));setAnswer(s,'q2','a');assert.ok(!evidence(s.answers).some(r=>r.question==='q15'));});
test('same-subset baseline denominator is reproducible',()=>{const s=filled();s.locked=freeze(s.answers);for(const p of s.locked.predictions)setAnswer(s,p.question,p.option||'skip');const a=stats(s);assert.equal(a.hits,a.predicted);assert.equal(a.baselineHits,a.trials.filter(t=>t.actual&&t.option&&t.actual===t.baseline).length);});

test('close friend and group friends never share a target key',()=>{const s=filled();setAnswer(s,'q1','b');const rows=evidence(s.answers);assert.ok(rows.some(r=>r.target==='chosen friend'));assert.ok(rows.some(r=>r.target==='friend'));const p=predict(QUESTIONS[25],s.answers);assert.ok(!p.sources.includes('q9'));});
test('unsupported options cannot borrow support from competitors',()=>{const p=predict(QUESTIONS[28],{q13:'a',q14:'a'});assert.equal(p.option,null);});
test('practice flag survives training edits and resume',()=>{const s=filled();s.locked=freeze(s.answers);s.testSeen=true;setAnswer(s,'q4','b');assert.equal(s.reviewed,true);assert.equal(restore(JSON.stringify(s)).reviewed,true);});

test('headline does not turn group directness into close-person directness',()=>{const a={q1:'b',q3:'a',q9:'a',q7:'c',q24:'d'};const i=identity(profile(a));assert.match(i.line,/friends in group situations/);assert.doesNotMatch(i.line,/discuss yesterday/);});
